/// <reference path="../externals.d.ts" />

import model = require('../core/Model');

export class GetTokenClientCredentialsResponse extends model.Model {

    /**
     * Access token to pass to subsequent API requests
     */
    access_token:string;

    /**
     * Type of token. Use this parameter in Authorization header of requests
     */
    token_type:string;

    /**
     * Issued access token TTL (time to live), in seconds
     */
    expires_in:number;

    /**
     * List of permissions allowed with this access token, white-space separated
     */
    scope:string;

    /**
     * Unique identifier of a client application passed by the client, or auto-generated by server if not specified in request
     */
    endpoint_id:string;

    getPropertyMappings():model.ModelPropertyMapping[] {

        return [
            {property: 'access_token', Class: null /* string */, isArray: false,isRequired: false},
            {property: 'token_type', Class: null /* string */, isArray: false,isRequired: false},
            {property: 'expires_in', Class: null /* number */, isArray: false,isRequired: false},
            {property: 'scope', Class: null /* string */, isArray: false,isRequired: false},
            {property: 'endpoint_id', Class: null /* string */, isArray: false,isRequired: false}
        ];

    }

    getClassName() {
        return 'GetTokenClientCredentialsResponse';
    }

    // CUSTOM METHODS
    // CUSTOM METHODS

}